# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import src.services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=src.services.models.upl)),
                ('text', models.TextField(max_length=20000)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
