# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-30 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import src.services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20160930_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=src.services.models.upl)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.Service')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': '\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438',
            },
        ),
    ]
