# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import src.rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20160725_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=src.rooms.models.upl_photos),
        ),
    ]
