# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20160901_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date_start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0434\u043e'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u043e\u0442'),
        ),
        migrations.AlterField(
            model_name='room',
            name='persons',
            field=models.IntegerField(verbose_name='\u041c\u0430\u043a\u0441. \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0447\u0435\u043b\u043e\u0432\u0435\u043a'),
        ),
    ]
