# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20160905_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date_end',
            field=models.CharField(default='0', max_length=255, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='date_start',
            field=models.CharField(default='0', max_length=255, verbose_name='\u0414\u0430\u0442\u0430 \u0441'),
            preserve_default=False,
        ),
    ]
