# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20160905_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='date_end',
            field=models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date_start',
            field=models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0441'),
        ),
        migrations.AlterField(
            model_name='room',
            name='text',
            field=models.TextField(max_length=4096, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u043e\u043c\u0435\u0440\u0430'),
        ),
    ]
