# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20160926_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='comfort',
            name='fa_icon',
            field=models.CharField(default='', max_length=255, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043d\u0430 \u0441\u0430\u0439\u0442\u0435'),
        ),
        migrations.AlterField(
            model_name='room',
            name='text',
            field=models.TextField(max_length=500, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u043e\u043c\u0435\u0440\u0430 (\u043d\u0435 \u0431\u043e\u043b\u0435\u0435 500 \u0437\u043d\u0430\u043a\u043e\u0432)'),
        ),
    ]
