# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-20 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u043e\u043c\u0435\u0440\u0430 (\u043d\u0435 \u0431\u043e\u043b\u0435\u0435 500 \u0437\u043d\u0430\u043a\u043e\u0432)'),
        ),
    ]
