# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 12:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=20000, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
    ]
