# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-03 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160929_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0430\u044f \u043f\u043e\u0447\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='map',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='\u041a\u043e\u0434 \u0434\u043b\u044f \u043a\u0430\u0440\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='phone_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d 1'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='phone_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d 2'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='phone_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d 3'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='skype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0421\u043a\u0430\u0439\u043f'),
        ),
    ]
