# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-03 10:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20161003_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='contacts_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=20000, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0430\u0445, \u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0438, \u0442\u0440\u0430\u043d\u0441\u0444\u0435\u0440\u0435'),
            preserve_default=False,
        ),
    ]
