# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20160219_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.IntegerField(choices=[(1, '\u0414\u043e\u043c'), (2, '\u0414\u0432\u043e\u0440'), (3, '\u041a\u043e\u043c\u043d\u0430\u0442\u044b'), (4, '\u041a\u0443\u0445\u043d\u044f')], default=1),
            preserve_default=False,
        ),
    ]
