# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import src.photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=src.photos.models.upl)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.IntegerField(choices=[(0, ''), (1, '\u0414\u043e\u043c'), (2, '\u0414\u0432\u043e\u0440'), (3, '\u041a\u043e\u043c\u043d\u0430\u0442\u044b'), (4, '\u041a\u0443\u0445\u043d\u044f')]),
        ),
    ]
